version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "TypeScript"
    assignees:
      - "46ki75"
    reviewers:
      - "46ki75"
    groups:
      notion-a2ui-updates:
        patterns:
          - "@notionhq/*"
          - "@a2ui/*"
          - "@elmethis/*"
