name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI (hermetic)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: just ci
        run: just ci

      - name: Install cargo-workspace-inheritance-check
        run: cargo install cargo-workspace-inheritance-check --locked --version 1.3.0

      - name: Workspace inheritance check
        run: cargo workspace-inheritance-check --promotion-failure
